apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mytestsandbox-tls
spec:
  secretName: mytestsandbox.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mytestsandbox.com
  dnsNames:
    - mytestsandbox.com
    - www.mytestsandbox.com